server:
  port: 8099
  servlet:
    context-path: /shopping
spring:
  datasource:
    username: root
    password: wang44
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/hostpital?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

  mvc:
    static-path-pattern: /**

    resources:
      static-locations: classpath:/static/

mybatis:
  configuration:
    map-underscore-to-camel-case: true